<Project>

  <PropertyGroup>
    <SolutionDir Condition="'$(SolutionDir)' == '' or '$(SolutionDir)' == '*Undefined*'">$(MSBuildThisFileDirectory)..\..\</SolutionDir>
    <KoreForgeAppLifecycleDocsTargetRoot Condition="'$(KoreForgeAppLifecycleDocsTargetRoot)' == ''">$(MSBuildProjectDirectory)\artifacts\KoreForge.AppLifecycle\</KoreForgeAppLifecycleDocsTargetRoot>
  </PropertyGroup>

</Project>

