<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <SolutionDir Condition="'$(SolutionDir)' == '' or '$(SolutionDir)' == '*Undefined*'">$(MSBuildProjectDirectory)\..\..\</SolutionDir>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="Testcontainers.Kafka" Version="4.8.1" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EventReader" VersionOverride="1.1.2" Aliases="EventReaderApp" />
    <PackageReference Include="EventProcessor" VersionOverride="1.1.2" />
  </ItemGroup>
</Project>